spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: system-service
          uri: lb://system-service
          predicates:
            - Path=/system/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
      discovery:
        locator:
          enabled: true

