server:
  port: 8088
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # Nacos 地址
#  ai:
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        options:
#          model: llama3.2:3b
#logging:
#  level:
#    org:
#      springframework:
#        web: debug
#        http.converter: debug